/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/categories": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all categories */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["CategoryDto"][]
            }
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/ingredients": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all ingredients */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["IngredientDto"][]
            }
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/testimonials": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all testimonials */
    get: {
      parameters: {
        query?: {
          limit?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["TestimonialDto"][]
            }
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/areas": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all areas */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["AreaDto"][]
            }
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/recipes": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all recipes (Cards) */
    get: {
      parameters: {
        query?: {
          authorId?: string
          limit?: number
          page?: number
          categoryIds?: string[]
          areaIds?: string[]
          ingredientIds?: string[]
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["RecipeCardDto"][]
              meta: components["schemas"]["PaginationDto"]
            }
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    put?: never
    /** Create Recipe */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          "multipart/form-data": components["schemas"]["CreateRecipeDto"] & {
            /** Format: binary */
            image: string
          }
        }
      }
      responses: {
        /** @description Successful response */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["IdParamDto"]
            }
          }
        }
        /** @description Validation failed */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiValidationErrorSchema"]
          }
        }
        /** @description Unauthorized - Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/recipes/my": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get user recipes (Cards) */
    get: {
      parameters: {
        query?: {
          page?: number
          limit?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["UserRecipeDto"][]
              meta: components["schemas"]["PaginationDto"]
            }
          }
        }
        /** @description Unauthorized - Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/recipes/popular": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get popular recipes (Cards) */
    get: {
      parameters: {
        query?: {
          limit?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["RecipeCardDto"][]
            }
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/recipes/favorite": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get user favorite recipes (Cards) */
    get: {
      parameters: {
        query?: {
          page?: number
          limit?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["RecipeCardDto"][]
              meta: components["schemas"]["PaginationDto"]
            }
          }
        }
        /** @description Unauthorized - Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/recipes/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Recipe by ID */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["RecipeDto"]
            }
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    put?: never
    post?: never
    /** Delete recipe */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized - Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/recipes/{id}/favorite": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Add recipe to user favorites */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized - Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    /** Delete recipe from user favorites */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized - Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/auth/signup": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Sign Up */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["SignUpDto"]
        }
      }
      responses: {
        /** @description Successful response */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["UserDto"]
            }
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/auth/signin": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Sign In */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          "application/json": components["schemas"]["SignInDto"]
        }
      }
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["SignInResponseDto"]
            }
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/auth/signout": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Sign Out */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful response */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized - Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/users/current": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Current user */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["UserProfileDto"]
            }
          }
        }
        /** @description Unauthorized - Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/users/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get user by ID */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["UserProfilePublicDto"]
            }
          }
        }
        /** @description Unauthorized - Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/users/{id}/followers": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get user followers */
    get: {
      parameters: {
        query?: {
          page?: number
          limit?: number
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["UserProfilePublicDto"][]
              meta: components["schemas"]["PaginationDto"]
            }
          }
        }
        /** @description Unauthorized - Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/users/{id}/following": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get user following */
    get: {
      parameters: {
        query?: {
          page?: number
          limit?: number
        }
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["UserProfilePublicDto"][]
              meta: components["schemas"]["PaginationDto"]
            }
          }
        }
        /** @description Unauthorized - Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/users/{id}/follow": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Follow user */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful response */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized - Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    /** Unfollow user */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful response */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized - Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/users/avatar": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update user avatar */
    patch: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          "multipart/form-data": {
            /**
             * Format: binary
             * @description File (jpg, png, etc.)
             */
            avatar: string
          }
        }
      }
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["UpdateAvatarResponseDto"]
            }
          }
        }
        /** @description Unauthorized - Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["ApiErrorSchema"]
          }
        }
      }
    }
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    IdParamDto: {
      id: string
    }
    SignUpDto: {
      name: string
      /** Format: email */
      email: string
      password: string
    }
    SignInDto: {
      /** Format: email */
      email: string
      password: string
    }
    LimitQueryDto: {
      /** @default 4 */
      limit: number
    }
    RecipesQueryDto: {
      authorId?: string
      /** @default 10 */
      limit: number
      /** @default 1 */
      page: number
      categoryIds?: string[]
      areaIds?: string[]
      ingredientIds?: string[]
    }
    CreateRecipeDto: {
      /** @example Borscht */
      title: string
      /** @example lorem ipsum dolor sit amet */
      description: string
      /** @example lorem ipsum dolor sit amet */
      instructions: string
      /** @example 180 */
      time: number
      /** @example 6462a6cd4c3d0ddd28897f95 */
      categoryId: string
      /** @example 6462a6f04c3d0ddd28897f9b */
      areaId: string
      /**
       * @description Введите массив ингредиентов в формате JSON. Пример: [{"ingredientId": "id123", "measure": "200g"}]
       * @example [{"ingredientId": "640c2dd963a319ea671e383b", "measure": "200g"}, {"ingredientId": "640c2dd963a319ea671e3860", "measure": "500g"}]
       */
      ingredients: string
    }
    ApiErrorSchema: {
      /** @example /api/v1/resource-example */
      path: string
      /** @example GET */
      method: string
      /** Format: date-time */
      timestamp: string
      message: string
    }
    ApiValidationErrorSchema: components["schemas"]["ApiErrorSchema"] & {
      /** @enum {string} */
      message?: "Validation failed"
      errors: {
        /** @example email */
        path: string
        /** @example Invalid input: expected string, received undefined */
        message: string
      }[]
    }
    CategoryDto: {
      id: string
      name: string
      description: string
    }
    IngredientDto: {
      /** @example string */
      id: string
      /** @example Egg */
      name: string
      /** @example lorem ipsum dolor sit amet */
      description: string
      /** @example https://example.com/image.jpg */
      imageURL: string
    }
    TestimonialDto: {
      /** @example string */
      id: string
      /** @example Artem */
      owner: string
      /** @example lorem ipsum dolor sit amet */
      text: string
    }
    AreaDto: {
      /** @example string */
      id: string
      /** @example Ukrainian */
      name: string
    }
    PaginationDto: {
      total: number
      page: number
      limit: number
    }
    RecipeDto: {
      /** @example string */
      id: string
      /** @example Borscht */
      title: string
      /** @example lorem ipsum dolor sit amet */
      description: string
      /** @example lorem ipsum dolor sit amet */
      instructions: string
      ingredients: {
        /** @example 200g */
        measure: string
        /** @example Meat */
        name: string
        /**
         * Format: uri
         * @example https://example.com/meet.jpg
         */
        imageURL: string
      }[]
      image: {
        /**
         * Format: uri
         * @example https://example.com/meet.jpg
         */
        original: string
        /**
         * Format: uri
         * @example https://example.com/meet.jpg
         */
        phone: string
        /**
         * Format: uri
         * @example https://example.com/meet.jpg
         */
        tablet: string
        /**
         * Format: uri
         * @example https://example.com/meet.jpg
         */
        desktop: string
        /**
         * Format: uri
         * @example https://example.com/meet.jpg
         */
        thumbnail: string
      }
      /** @example string */
      ownerId: string
      /**
       * Format: uri
       * @example https://avatar.com/1.jpg
       */
      ownerAvatarURL: string | null
      /** @example Ivan */
      ownerName: string
      /** @example 60 */
      time: number
      /** @example Soup */
      category: string
      /** @example Ukrainian */
      area: string
    }
    RecipeCardDto: {
      /** @example string */
      id: string
      /** @example Borscht */
      title: string
      /** @example lorem ipsum dolor sit amet */
      instructions: string
      image: {
        /**
         * Format: uri
         * @example https://example.com/meet.jpg
         */
        original: string
        /**
         * Format: uri
         * @example https://example.com/meet.jpg
         */
        phone: string
        /**
         * Format: uri
         * @example https://example.com/meet.jpg
         */
        tablet: string
        /**
         * Format: uri
         * @example https://example.com/meet.jpg
         */
        desktop: string
        /**
         * Format: uri
         * @example https://example.com/meet.jpg
         */
        thumbnail: string
      }
      /** @example string */
      ownerId: string
      /**
       * Format: uri
       * @example https://avatar.com/1.jpg
       */
      ownerAvatarURL: string | null
      /** @example Ivan */
      ownerName: string
    }
    UserRecipeDto: {
      /** @example Borscht */
      title: string
      /** @example lorem ipsum dolor sit amet */
      instructions: string
      image: {
        /**
         * Format: uri
         * @example https://example.com/meet.jpg
         */
        original: string
        /**
         * Format: uri
         * @example https://example.com/meet.jpg
         */
        phone: string
        /**
         * Format: uri
         * @example https://example.com/meet.jpg
         */
        tablet: string
        /**
         * Format: uri
         * @example https://example.com/meet.jpg
         */
        desktop: string
        /**
         * Format: uri
         * @example https://example.com/meet.jpg
         */
        thumbnail: string
      }
    }
    UserDto: {
      id: string
      name: string
      email: string
      avatarURL: string | null
    }
    UserProfileDto: components["schemas"]["UserDto"] & {
      totalRecipes: number
      totalFollowers: number
      totalFavoriteRecipes: number
      totalFollowing: number
    }
    UserProfilePublicDto: {
      id: string
      name: string
      email: string
      avatarURL: string | null
      totalRecipes: number
      totalFollowers: number
    }
    SignInResponseDto: components["schemas"]["UserProfileDto"] & {
      token: string
    }
    UpdateAvatarResponseDto: {
      avatarUrl: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
